// flow-typed signature: 2f2c490964365b5a7b48d741acd41b47
// flow-typed version: <<STUB>>/await-to-js_v^2.0.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'await-to-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'await-to-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'await-to-js/dist/await-to-js.es5' {
  declare module.exports: any;
}

declare module 'await-to-js/dist/await-to-js.umd' {
  declare module.exports: any;
}

declare module 'await-to-js/dist/docs/assets/js/main' {
  declare module.exports: any;
}

declare module 'await-to-js/dist/docs/assets/js/search' {
  declare module.exports: any;
}

// Filename aliases
declare module 'await-to-js/dist/await-to-js.es5.js' {
  declare module.exports: $Exports<'await-to-js/dist/await-to-js.es5'>;
}
declare module 'await-to-js/dist/await-to-js.umd.js' {
  declare module.exports: $Exports<'await-to-js/dist/await-to-js.umd'>;
}
declare module 'await-to-js/dist/docs/assets/js/main.js' {
  declare module.exports: $Exports<'await-to-js/dist/docs/assets/js/main'>;
}
declare module 'await-to-js/dist/docs/assets/js/search.js' {
  declare module.exports: $Exports<'await-to-js/dist/docs/assets/js/search'>;
}
