// flow-typed signature: b27bd30614a7ccf841be9930ff129346
// flow-typed version: <<STUB>>/serverless-offline-scheduler_v^0.3.3/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-offline-scheduler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-offline-scheduler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless-offline-scheduler/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'serverless-offline-scheduler/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'serverless-offline-scheduler/lib/scheduler' {
  declare module.exports: any;
}

declare module 'serverless-offline-scheduler/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless-offline-scheduler/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'serverless-offline-scheduler/coverage/lcov-report/prettify'>;
}
declare module 'serverless-offline-scheduler/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'serverless-offline-scheduler/coverage/lcov-report/sorter'>;
}
declare module 'serverless-offline-scheduler/index' {
  declare module.exports: $Exports<'serverless-offline-scheduler'>;
}
declare module 'serverless-offline-scheduler/index.js' {
  declare module.exports: $Exports<'serverless-offline-scheduler'>;
}
declare module 'serverless-offline-scheduler/lib/scheduler.js' {
  declare module.exports: $Exports<'serverless-offline-scheduler/lib/scheduler'>;
}
declare module 'serverless-offline-scheduler/lib/utils.js' {
  declare module.exports: $Exports<'serverless-offline-scheduler/lib/utils'>;
}
