// flow-typed signature: 1d6ce37f2eec9dda8a28933dd373f00a
// flow-typed version: <<STUB>>/serverless-dynamodb-local_v^0.2.30/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-dynamodb-local'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-dynamodb-local' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless-dynamodb-local/src/seeder' {
  declare module.exports: any;
}

declare module 'serverless-dynamodb-local/test/indexTest' {
  declare module.exports: any;
}

declare module 'serverless-dynamodb-local/test/testItems' {
  declare module.exports: any;
}

declare module 'serverless-dynamodb-local/test/testTable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless-dynamodb-local/index' {
  declare module.exports: $Exports<'serverless-dynamodb-local'>;
}
declare module 'serverless-dynamodb-local/index.js' {
  declare module.exports: $Exports<'serverless-dynamodb-local'>;
}
declare module 'serverless-dynamodb-local/src/seeder.js' {
  declare module.exports: $Exports<'serverless-dynamodb-local/src/seeder'>;
}
declare module 'serverless-dynamodb-local/test/indexTest.js' {
  declare module.exports: $Exports<'serverless-dynamodb-local/test/indexTest'>;
}
declare module 'serverless-dynamodb-local/test/testItems.js' {
  declare module.exports: $Exports<'serverless-dynamodb-local/test/testItems'>;
}
declare module 'serverless-dynamodb-local/test/testTable.js' {
  declare module.exports: $Exports<'serverless-dynamodb-local/test/testTable'>;
}
